CREATE TABLE `manufatura`.`item_poack_atual` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `po` varchar(19) DEFAULT NULL,
  `linha` varchar(13) DEFAULT NULL,
  `tipo_po` varchar(14) DEFAULT NULL,
  `action` varchar(14) DEFAULT NULL,
  `status` varchar(14) DEFAULT NULL,
  `qtde` double DEFAULT NULL,
  `prio` varchar(13) DEFAULT NULL,
  `material` double DEFAULT NULL,
  `part_number` varchar(31) DEFAULT NULL,
  `descricao_do_material` varchar(50) DEFAULT NULL,
  `ncm` double DEFAULT NULL,
  `dt_remessa` datetime DEFAULT NULL,
  `dt_entrega` datetime DEFAULT NULL,
  `dt_promessa` datetime DEFAULT NULL,
  `lead_time1` varchar(15) DEFAULT NULL,
  `no_ngc_dt_en` double DEFAULT NULL,
  `no_ngc_dt_pr` varchar(11) DEFAULT NULL,
  `sta_aprv` varchar(13) DEFAULT NULL,
  `ack` varchar(11) DEFAULT NULL,
  `motivo` varchar(29) DEFAULT NULL,
  `nf_forn` varchar(15) DEFAULT NULL,
  `status_nf` varchar(12) DEFAULT NULL,
  `dt_grace` datetime DEFAULT NULL,
  `lead_time2` varchar(18) DEFAULT NULL,
  `ciclo` double DEFAULT NULL,
  `remessa` double DEFAULT NULL,
  `entrega` double DEFAULT NULL,
  `criacao` varchar(10) DEFAULT NULL,
  `unidade` varchar(12) DEFAULT NULL,
  `descricao_prioridade` varchar(28) DEFAULT NULL,
  `revpn` varchar(64) DEFAULT NULL COMMENT 'Revisão do Part Number (coluna nova da planilha POACK)',
  `preco_unit` double DEFAULT NULL,
  `preco_bruto` double DEFAULT NULL,
  `por` double DEFAULT NULL,
  `dep_armaz` varchar(13) DEFAULT NULL,
  `acao_dias` double DEFAULT NULL,
  `centro` varchar(14) DEFAULT NULL,
  `peca_reposicao` varchar(13) DEFAULT NULL,
  `doc_vinculado` varchar(10) DEFAULT NULL,
  `embalagem` varchar(10) DEFAULT NULL,
  `placa` varchar(10) DEFAULT NULL,
  `dt_ponto_uso` varchar(10) DEFAULT NULL,
  `buffer` double DEFAULT NULL,
  `no_acomp` varchar(20) DEFAULT NULL,
  `usuario` varchar(19) DEFAULT NULL,
  `nome` varchar(42) DEFAULT NULL,
  `ultima_acao` varchar(25) DEFAULT NULL,
  `chapa_fluxo` double DEFAULT NULL,
  `ct_origem` varchar(14) DEFAULT NULL,
  `ct_descricao` varchar(50) DEFAULT NULL,
  `ct_centro` varchar(14) DEFAULT NULL,
  `aging_ct` double DEFAULT NULL,
  `tnf` varchar(14) DEFAULT NULL,
  `1a_nf` double DEFAULT NULL,
  `ult_nf` double DEFAULT NULL,
  `emf_previsto` datetime DEFAULT NULL,
  `qtd_recebida` double DEFAULT NULL,
  `qtd_pendente` double DEFAULT NULL,
  `valor_recebido` double DEFAULT NULL,
  `mensagem` text,
  `ativo` varchar(10) DEFAULT NULL,
  `popup` varchar(10) DEFAULT NULL,
  `fse` varchar(10) DEFAULT NULL,
  `item_nf` double DEFAULT NULL,
  `dt_emissao_nf` datetime DEFAULT NULL,
  `dt_coleta_nf` varchar(10) DEFAULT NULL,
  `dt_plan_coleta_nf` varchar(10) DEFAULT NULL,
  `dt_cadastro_nf` datetime DEFAULT NULL,
  `dt_portaria_nf` datetime DEFAULT NULL,
  `tipo_nf` varchar(11) DEFAULT NULL,
  `texto` text,
  `novo_texto` varchar(13) DEFAULT NULL,
  `data_arquivo` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_dt_promessa` (`dt_promessa`),
  KEY `idx_item_poack` (`po`,`linha`,`action`),
  KEY `idx_item_poack_po_ref` (`po`),
  KEY `idx_item_poack_linha_ref` (`linha`),
  KEY `idx_item_poack_po_linha_comp` (`po`,`linha`),
  KEY `idx_item_poack_atual_performance` (`po`,`linha`,`action`),
  KEY `idx_po_linha` (`po`,`linha`),
  KEY `idx_ipa_po_linha_action` (`po`,`linha`,`action`)
) ENGINE=InnoDB AUTO_INCREMENT=848363 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `manufatura`.`objeto_dezena_atual` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `of` varchar(255) DEFAULT NULL,
  `data_rota` datetime DEFAULT NULL,
  `rota` varchar(255) DEFAULT NULL,
  `critico` varchar(255) DEFAULT NULL,
  `acionamento_direto` varchar(255) DEFAULT NULL,
  `tipo` varchar(255) DEFAULT NULL,
  `prio_vmx` varchar(255) DEFAULT NULL,
  `sep` varchar(255) DEFAULT NULL,
  `data_registro` datetime DEFAULT NULL,
  `spr` varchar(255) DEFAULT NULL,
  `final_intermediario` varchar(50) DEFAULT NULL,
  `sts` varchar(50) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `de_simul` varchar(255) DEFAULT NULL,
  `cobertura_dinamica` varchar(45) DEFAULT NULL,
  `prev_fat` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_objeto_dezena_of` (`of`),
  KEY `idx_objeto_dezena_of_ref` (`of`),
  KEY `idx_objeto_dezena_data_reg` (`data_registro` DESC),
  KEY `idx_objeto_dezena_atual_of` (`of`,`prio_vmx`,`data_rota`,`acionamento_direto`),
  KEY `idx_of` (`of`),
  KEY `idx_of_corrigida` (`of`)
) ENGINE=InnoDB AUTO_INCREMENT=77023 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `manufatura`.`ordem_fabricacao` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `pedido` int DEFAULT NULL,
  `oc_linha` varchar(26) DEFAULT NULL,
  `of` varchar(23) DEFAULT NULL,
  `pn` varchar(55) DEFAULT NULL,
  `descricao` varchar(97) DEFAULT NULL,
  `cliente` varchar(35) DEFAULT NULL,
  `data` datetime DEFAULT NULL,
  `qtde_original` int DEFAULT NULL,
  `qtde` int DEFAULT NULL,
  `oc` varchar(24) DEFAULT NULL,
  `linha` varchar(14) DEFAULT NULL,
  `status_of` varchar(20) DEFAULT NULL,
  `dt_entrega` varchar(10) DEFAULT NULL,
  `dt_promessa` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_oc_linha_pedido` (`oc`,`linha`,`pedido`),
  KEY `idx_ordem_of_principal` (`of`),
  KEY `idx_ordem_data_criacao` (`data`),
  KEY `idx_ordem_oc_linha_ref` (`oc_linha`),
  KEY `idx_ordem_part_number` (`pn`),
  KEY `idx_ordem_cliente_ref` (`cliente`),
  KEY `idx_ordem_status_atual` (`status_of`),
  KEY `idx_ordem_pedido_ref` (`pedido`),
  KEY `idx_ordem_oc_linha_join_v2` (`oc`,`linha`),
  KEY `idx_ordem_fabricacao_performance` (`status_of`,`of`,`oc`,`linha`,`pn`,`pedido`),
  KEY `idx_ordem_fabricacao_of` (`of`),
  KEY `idx_ordem_fabricacao_oc_linha` (`oc`,`linha`),
  KEY `idx_ordem_fabricacao_of_pn` (`of`,`pn`),
  KEY `idx_oc_linha` (`oc_linha`),
  KEY `idx_of` (`of`)
) ENGINE=InnoDB AUTO_INCREMENT=28379 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `manufatura`.`poack_cabecalho` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `identificacao` int DEFAULT NULL,
  `po` varchar(19) DEFAULT NULL,
  `fornecedor` varchar(255) DEFAULT NULL,
  `nome_do_fornecedor` varchar(33) DEFAULT NULL,
  `empresa` varchar(14) DEFAULT NULL,
  `nome_da_empresa` varchar(29) DEFAULT NULL,
  `tipo_po` varchar(14) DEFAULT NULL,
  `descricao_da_po` varchar(30) DEFAULT NULL,
  `data_criacao` datetime DEFAULT NULL,
  `usuario` varchar(20) DEFAULT NULL,
  `nome_do_usuario` varchar(50) DEFAULT NULL,
  `cond_pagto` varchar(14) DEFAULT NULL,
  `descricao_cond_pagto` varchar(41) DEFAULT NULL,
  `org_compra` varchar(14) DEFAULT NULL,
  `descricao_org_compra` varchar(25) DEFAULT NULL,
  `comprador` varchar(13) DEFAULT NULL,
  `nome_do_comprador` varchar(28) DEFAULT NULL,
  `moeda` varchar(13) DEFAULT NULL,
  `descricao_moeda` varchar(23) DEFAULT NULL,
  `incoterms_1` varchar(13) DEFAULT NULL,
  `descricao` varchar(33) DEFAULT NULL,
  `incoterms_2` varchar(23) DEFAULT NULL,
  `emissor_fatura` varchar(13) DEFAULT NULL,
  `nome_emissor_fatura` varchar(13) DEFAULT NULL,
  `valor_po` varchar(20) DEFAULT NULL,
  `contrato` varchar(19) DEFAULT NULL,
  `data_arquivo` datetime DEFAULT NULL,
  `data_importacao` datetime DEFAULT NULL,
  `planilha` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=822483 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `manufatura`.`indicadores_poack` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `dt_registro` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ordens_ra` int DEFAULT NULL,
  `vencidos_ab` int DEFAULT NULL,
  `vencidos_at` int DEFAULT NULL,
  `entrega_maior_promessa_ab` int DEFAULT NULL,
  `entrega_maior_promessa_at` int DEFAULT NULL,
  `simulada_maior_entrega_ab` int DEFAULT NULL,
  `simulada_maior_entrega_at` int DEFAULT NULL,
  `ciclo_zerado` int DEFAULT NULL,
  `oc_maior_180_dias` int DEFAULT NULL,
  `priorizacoes` decimal(9,4) DEFAULT NULL,
  `oc_remessa_passado` decimal(9,4) DEFAULT NULL,
  `OTD` decimal(9,4) DEFAULT NULL,
  `ciclo` decimal(9,4) DEFAULT NULL,
  `total_multas` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uq_indicadores_poack_dt_registro` (`dt_registro`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `manufatura`.`pn_cobertura_atual` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `identificacao` int DEFAULT NULL,
  `material` double DEFAULT NULL,
  `pn` varchar(29) DEFAULT NULL,
  `descricao` varchar(10) DEFAULT NULL,
  `programa` varchar(10) DEFAULT NULL,
  `qtde_saldo` double DEFAULT NULL,
  `stts_atendimento` varchar(20) DEFAULT NULL,
  `prio` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=426 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `pbi`.`previsao_faturamento` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Fonte` varchar(32) DEFAULT NULL,
  `Nro Doc` varchar(16) DEFAULT NULL,
  `Parcela` int DEFAULT NULL,
  `Empresa` varchar(128) DEFAULT NULL,
  `Emissão` date DEFAULT NULL,
  `Vencimento` date DEFAULT NULL,
  `Valor` decimal(15,2) DEFAULT NULL,
  `dt_atualização` date DEFAULT (curdate()),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=55225 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci